### ISSUE TITLE
Client IP address

### ISSUE THREAD

**Issue by ajvdw** [MichaelDvP/EMS-ESP32#1]
Is it possible to add one or two sensors that deliver the EMS-ESP ip address and mac address?
Similar to the "WiFi strength".
I'm using DHCP and need to login to my modem to find out the IP address that was handed out. MDNS messages are killed by the router, so accessing by hostname does not work either.

**Comment by MichaelDvP** [comment]
This is published on startup in topic: info. For adding a HA-sensor to HA-autodiscovery please ask in official ems-esp GH.
